# Generated by Django 5.1.1 on 2024-09-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('location', models.TextField()),
                ('date', models.DateField(verbose_name='')),
                ('time', models.TimeField()),
            ],
        ),
    ]
